<?php
/**
 * underscore.js template for the dialog for the cred_delete_post_link shortcode.
 *
 * @since m2m
 */
?>
<script type="text/html" id="tmpl-cred-delete-post-link-template">
	<#
	data = _.extend(
		data,
		{
			attributes: {
				options: {
					header: '<?php echo esc_js( __( 'Options', 'wp-cred' ) ); ?>',
					fields: {
						action: {
							label: '<?php echo esc_js( __( 'Action to perform', 'wp-cred' ) ); ?>',
							type: 'radio',
							options: {
								trash: '<?php echo esc_js( __( 'Trash the post', 'wp-cred' ) ); ?>',
								delete: '<?php echo esc_js( __( 'Delete the post', 'wp-cred' ) ); ?>'
							},
							defaultForceValue: 'trash'
						},
						text: {
							label: '<?php echo esc_js( __( 'Link text', 'wp-cred' ) ); ?>',
							type: 'content',
							required: true,
							defaultValue: '<?php echo esc_js( __( 'Delete %TITLE%', 'wp-cred' ) ); ?>'
						},
						redirect: {
							label: '<?php echo esc_js( __( 'Action after deleting the post', 'wp-cred' ) ); ?>',
							type: 'radio',
							options: {
								'': '<?php echo esc_js( __( 'Do nothing', 'wp-cred' ) ); ?>',
								'reload': '<?php echo esc_js( __( 'Reload the current page', 'wp-cred' ) ); ?>',
								toolsetCombo: '<?php echo esc_js( __( 'Redirect to another page', 'wp-cred' ) ); ?>'
							},
							defaultForceValue: 'reload'
						},
						'toolsetCombo:redirect': {
							type: 'ajaxSelect2',
							action: 'toolset_select2_suggest_posts_by_title',
							nonce: '<?php echo wp_create_nonce( Toolset_Ajax::CALLBACK_SELECT2_SUGGEST_POSTS_BY_TITLE ); ?>',
							placeholder: '<?php echo esc_js( __( 'Search for a page to redirect to', 'wp-cred' ) ); ?>',
							hidden: true
						},
					}
				},
				messageOptions: {
					header: '<?php echo esc_js( __( 'Confirmation messages', 'wp-cred' ) ); ?>',
					fields: {
						message_show: {
							label: '<?php echo esc_js( __( 'Message before deleting', 'wp-cred' ) ); ?>',
							type: 'radio',
							options: {
								'0': '<?php echo esc_js( __( 'Do not show a message before deleting the post', 'wp-cred' ) ); ?>',
								toolsetCombo: '<?php echo esc_js( __( 'Show a message before deleting the post', 'wp-cred' ) ); ?>'
							},
							defaultValue: 'toolsetCombo'
						},
						'toolsetCombo:message_show': {
							type: 'text',
							defaultForceValue: '<?php echo esc_js( __( 'Are you sure you want to delete this post?', 'wp-cred' ) ); ?>'
						},
						message_after: {
							label: '<?php echo esc_js( __( 'Message after deleting', 'wp-cred' ) ); ?>',
							type: 'radio',
							options: {
								'': '<?php echo esc_js( __( 'Do not show a message after deleting the post', 'wp-cred' ) ); ?>',
								toolsetCombo: '<?php echo esc_js( __( 'Show a message after deleting the post', 'wp-cred' ) ); ?>'
							},
							defaultValue: ''
						},
						'toolsetCombo:message_after': {
							type: 'text',
							defaultForceValue: '<?php echo esc_js( __( 'Post deleted', 'wp-cred' ) ); ?>',
							hidden: true
						}
					}
				},
				styleOptions: {
					header: '<?php echo esc_js( __( 'Style options', 'wp-cred' ) ); ?>',
					fields: {
						class: {
							label: '<?php echo esc_js( __( 'Class', 'wp-cred' ) ); ?>',
							type: 'text',
							description: '<?php echo esc_js( __( 'Space-separated list of classnames that will be added to the anchor HTML tag.', 'wp-cred' ) ); ?>'
						},
						style: {
							label: '<?php echo esc_js( __( 'Style', 'wp-cred' ) ); ?>',
							type: 'text',
							description: '<?php echo esc_js( __( 'Inline styles that will be added to the anchor HTML tag.', 'wp-cred' ) ); ?>'
						}
					}
				},
				postSelection: {
					header: '<?php echo esc_js( __( 'Post selection', 'wp-cred' ) ); ?>',
					fields: {
						post: {
							label: '<?php echo esc_js( __( 'Post to delete', 'wp-cred' ) ); ?>',
							type: 'post',
							defaultValue: 'current'
						}
					}
				}
			}
		}
	);
	#>
	<# print( data.templates.dialog( data ) ); #>
</script>
